import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Josefin_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const researcher = localFont({
  src: [
    { path: "../public/fonts/researcher-researcher-thin-200.ttf", weight: "200", style: "normal" },
    { path: "../public/fonts/researcher-researcher-squid-700.ttf", weight: "300", style: "normal" },
    { path: "../public/fonts/researcher-researcher-regular-400.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/researcher-researcher-bold-700.ttf", weight: "700", style: "normal" },
  ],
});

const josefinSans = Josefin_Sans({ weight: "400", subsets: ["latin"] });
console.log(researcher.style);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-[#0f1012]">{children}</body>
      </html>
    </ClerkProvider>
  );
}
